// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe9Xl3Cj2bPkR5nh0vqulJLeHXaCZLWWQ',
    appId: '1:399866501379:web:879fc78eaa007f7c5a7136',
    messagingSenderId: '399866501379',
    projectId: 'cmsc23-final-project-54c2c',
    authDomain: 'cmsc23-final-project-54c2c.firebaseapp.com',
    storageBucket: 'cmsc23-final-project-54c2c.firebasestorage.app',
    measurementId: 'G-XE5Y6DNLW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe72gR9EcoslUy3JTcbP_HvSqRit5NmKQ',
    appId: '1:399866501379:android:1c625bfba44253ad5a7136',
    messagingSenderId: '399866501379',
    projectId: 'cmsc23-final-project-54c2c',
    storageBucket: 'cmsc23-final-project-54c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5mQbRszkKUVAXjA7255NKhSbrDeqkknU',
    appId: '1:399866501379:ios:efea83a103d83e895a7136',
    messagingSenderId: '399866501379',
    projectId: 'cmsc23-final-project-54c2c',
    storageBucket: 'cmsc23-final-project-54c2c.firebasestorage.app',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5mQbRszkKUVAXjA7255NKhSbrDeqkknU',
    appId: '1:399866501379:ios:efea83a103d83e895a7136',
    messagingSenderId: '399866501379',
    projectId: 'cmsc23-final-project-54c2c',
    storageBucket: 'cmsc23-final-project-54c2c.firebasestorage.app',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe9Xl3Cj2bPkR5nh0vqulJLeHXaCZLWWQ',
    appId: '1:399866501379:web:caf4f50321a7644f5a7136',
    messagingSenderId: '399866501379',
    projectId: 'cmsc23-final-project-54c2c',
    authDomain: 'cmsc23-final-project-54c2c.firebaseapp.com',
    storageBucket: 'cmsc23-final-project-54c2c.firebasestorage.app',
    measurementId: 'G-HM8JGEH75F',
  );
}
